### ISSUE TITLE
Errno::ENOMEM in UploadsController#create

### ISSUE THREAD

**Issue by scriptures4life** [wesabe/mesabe#23]
I am thinking this is a memory issue... I am running VirtualBox on a MBP with 4GB ram.  The box has 4.5GB free HD space, and is allocated 512MB ram and 128MB ram.  (The box would not start with the default value of VRAM.)

Thanks!

Errno::ENOMEM in UploadsController#create

Cannot allocate memory - /usr/bin/ruby1.8 /tmp/systemu_mesabe_1423_1552_0.624356313704616_1/program
Rails.root: /home/mesabe/wesabe/pfc

Application Trace | Framework Trace | Full Trace
lib/makeofx2.rb:46:in `convert'
app/models/upload.rb:186:in`convert_to_ofx2'
app/models/upload.rb:115:in `generate'
app/controllers/uploads_controller.rb:120:in`create'
Request

Parameters:

{"authenticity_token"=>"GianI/H+DgWSl8679uebx5YrCU3dfsvd3XZjkXhq6Tk=",
 "statement"=>#File:/tmp/RackMultipart20110219-1552-1vq26hp-0}
Show session dump

Show env dump

Response

Headers:

None

**Comment by scriptures4life** [comment]
Just thought I'd let you know the Rails server is taking up 723.4 MB of RAM!  Is there any reason for this?
